### ISSUE TITLE
Remove redundant files

### ISSUE THREAD

**Issue by FooBarWidget** [rossf7/traveling-elasticrawl#1]
I've written [a guide on reducing the size of packages](https://github.com/phusion/traveling-ruby/blob/master/REDUCING_PACKAGE_SIZE.md) by removing redundant files. By following the method in the guide, you can reduce your package size by 16 MB uncompressed, or by 3 MB compressed.

There are also a bunch of .so files in your OS X package, which you can remove.

Other files that I've found you can remove:

 * `*.o` files
 * `*.md` files
 * lib/vendor/ruby/2.1.0/gems/unf_ext-0.0.6/ext

By removing all of these too, I was able to reduce your OS X package from 22 MB compressed to 11 MB compressed.

**Comment by rossf7** [comment]
I've updated my Rakefile to delete the redundant files. New package sizes are

* Linux x86. 11MB (63 MB)
* Linux x86_64. 11MB (65 MB)
* OS X. 12 MB (66 MB)

which is a big improvement. Thanks for raising this.

**Comment by FooBarWidget** [comment]
I noticed that the unf_ext extension isn't packaged by Traveling Ruby, but you are using it. I'll package it in the next version, so be sure to update your packages too.
